### ISSUE TITLE
Login and sign up not functioning properly, app crashes sometimes 

### ISSUE THREAD

**Issue by michaelNgiri** [michaelNgiri/MedicSmart#1]

**Comment by DreamyPhobic** [comment]
@michaelNgiri  Can i work on this issue?

**Comment by secminhr** [comment]
@DreamyPhobic Maybe you can just try to fix it.
I also working on it haha

**Comment by michaelNgiri** [comment]
@DreamyPhobic Sure you can work on it 

All contributions are welcome
